### ISSUE TITLE
upload final pretrained weights

### ISSUE THREAD

**Issue by jcpeterson** [ShehabMMohamed/TinyImageNet-KaggleCompetition#1]
any chance you can?

**Comment by ShehabCE** [comment]
Sure thing. This is the last checkpoint I have found, ~82%
Link to weights file  [https://drive.google.com/open?id=0BzF5BeFv5ZRjXzlVTEJQZXcyME0](url)

**Comment by jcpeterson** [comment]
Thanks!!

**Comment by ShehabCE** [comment]
Granted

**Comment by ArighnaIITG** [comment]
Hey!! Can you please lend the pre-trained weights?
